apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-deploy-run-
spec:
  pipelineRef:
    name: petclinic-deploy
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: app-source-pvc
    # volumeClaimTemplate:
    #   spec:
    #     accessModes:
    #       - ReadWriteOnce 
    #     resources:
    #       requests:
    #         storage: 1Gi
  - name: maven-cache
    persistentVolumeClaim:
      claimName: maven-cache-pvc
  - name: maven-settings
    configMap:
      name: maven-settings