---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mapit-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/siamaksade/mapit-spring.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mapit-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/mapit-spring:latest